repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v2.1.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  # - repo: https://github.com/Lucas-C/pre-commit-hooks
  #   rev: v1.1.6
  #   hooks:
  #     - id: forbid-tabs
  # - repo: https://github.com/psf/black
  #   rev: 20.8b0
  #   hooks:
  #     - id: black
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v0.700"
  #   hooks:
  #     - id: mypy
  #       args:
  #         - --ignore-missing-imports
  # - repo: local
  #   hooks:
  #     - id: flake8
  #       name: flake8
  #       language: system
  #       entry: poetry run flake8
  #       types: [python]
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system # system -> The tools need to be installed locally
        types: [python] # file type
